services:
  - mysql
  - rabbitmq

language: python

matrix:
  include:
    - python: "2.7"
      env: PROJECT=idaplugin
    - python: "3.5"
      env: PROJECT=idaplugin
    - python: "2.7"
      env: PROJECT=server DJANGO_SETTINGS_MODULE='rematch.settings.debug'
    - python: "3.5"
      env: PROJECT=server DJANGO_SETTINGS_MODULE='rematch.settings.production'

branches:
  only:
    - master

# Handle git submodules ourselves to replace ssh login with https login
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - if [ ${PROJECT} = "server" ]; then
      set +vx;
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      bash ./miniconda.sh -b -p ${HOME}/miniconda;
      export PATH=${HOME}/miniconda/bin:$PATH;
      conda info -a;
      conda update --yes conda;
      conda install --yes python=${TRAVIS_PYTHON_VERSION} atlas numpy scipy scikit-learn;
    fi;
  - if [ -f ${PROJECT}/requirements.txt ]; then pip install -r ${PROJECT}/requirements.txt ; fi
  - if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt ; fi
  - pip install flake8
  - pip install pytest-cov coveralls

before_script:
  - if [ ${PROJECT} = "server" ]; then mysql -e 'SHOW VARIABLES LIKE "%version%";' ; fi;

script:
  - flake8 ./${PROJECT} --show-source --statistics
  - if [ -d ./tests/${PROJECT} ]; then flake8 ./tests/${PROJECT} --show-source ; fi
  - if [ -d ./tests/${PROJECT} ]; then py.test ./${PROJECT} ./tests/${PROJECT} --verbose --cov-report= --cov=$PROJECT ; fi
  - ./setup.py ${PROJECT} sdist --formats=zip ; pip install ./dist/rematch-${PROJECT}-*.zip

after_success:
  - if [ -d ./tests/${PROJECT} ]; then coveralls ; fi
